#!/usr/bin/env python3
"""Extract the Linux VGA 8x16 font from the kernel source into web assets.

Source of truth: linux-7.2.8/lib/fonts/font_8x16.c  (there is no `font8x16.h`
in 7.2.8).  The file defines:

    #define FONTDATAMAX 4096
    static const struct font_data fontdata_8x16 = {
        { 0, 0, FONTDATAMAX, 0 }, {
        0x00, /* 00000000 */
        ...
    }};

i.e. 256 glyphs * 16 rows, one byte per row, MSB = leftmost pixel.

Gotcha: the per-row comments also contain "0xNN" (in the `/* N 0xNN 'c' */`
char-code banners), which would inflate a naive hex scan from 4096 to 4352.
Comments are stripped before scanning.

Outputs:
  assets/font8x16.bin    raw 4096 bytes (canonical)
  src/font.data.js       window.LW.FONT_B64 = "<base64 of the 4096 bytes>"
"""

import argparse
import base64
import os
import re
import subprocess
import sys

DEFAULT_TARBALL = "/home/Yin/Downloads/linux-7.2.8.tar.xz"
FONT_MEMBER = "linux-7.2.8/lib/fonts/font_8x16.c"
FONTDATAMAX = 4096

# Verified reference glyph: 'A' (0x41).
REF_A = bytes.fromhex("00 00 10 38 6c c6 c6 fe c6 c6 c6 c6 00 00 00 00")


def project_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read_font_source(tarball: str) -> str:
    """Return the C source of font_8x16.c, using the cache when possible."""
    cache_dir = os.path.join(project_root(), "tools", ".cache")
    os.makedirs(cache_dir, exist_ok=True)
    cached = os.path.join(cache_dir, "font_8x16.c")
    if os.path.exists(cached):
        with open(cached, "rb") as fh:
            return fh.read().decode("latin-1")

    if not os.path.exists(tarball):
        raise SystemExit(
            f"neither the cache ({cached}) nor the tarball ({tarball}) is "
            f"available; point the tool at a linux-7.2.8 tarball"
        )

    # `tar -xJOf` (explicit xz + stdout): plain `-xO` errors with "missing -f".
    out = subprocess.check_output(["tar", "-xJOf", tarball, FONT_MEMBER])
    with open(cached, "wb") as fh:
        fh.write(out)
    return out.decode("latin-1")


def parse_font(text: str) -> bytes:
    stripped = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    tokens = re.findall(r"0x([0-9a-fA-F]{2})\b", stripped)
    if len(tokens) != FONTDATAMAX:
        raise SystemExit(
            f"expected {FONTDATAMAX} font bytes, found {len(tokens)} "
            f"(did the source layout change?)"
        )
    return bytes(int(t, 16) for t in tokens)


def self_test(data: bytes) -> None:
    def check(ok: bool, what: str) -> None:
        if not ok:
            raise SystemExit(f"self-test FAILED: {what}")
        print(f"  ok: {what}")

    check(len(data) == FONTDATAMAX, f"payload is {FONTDATAMAX} bytes")
    check(len(base64.b64encode(data)) == 5464, "base64 length is 5464")
    check(data[0x41 * 16:0x41 * 16 + 16] == REF_A, "'A' (0x41) matches reference")
    check(all(b == 0 for b in data[0:16]), "glyph 0 is blank")
    check(all(b == 0 for b in data[0x20 * 16:0x20 * 16 + 16]), "space (0x20) is blank")
    check(all(b == 0 for b in data[-16:]), "last glyph is blank")


def write_assets(data: bytes) -> None:
    root = project_root()
    bin_path = os.path.join(root, "assets", "font8x16.bin")
    js_path = os.path.join(root, "src", "font.data.js")

    with open(bin_path, "wb") as fh:
        fh.write(data)

    b64 = base64.b64encode(data).decode("ascii")
    header = (
        "// GENERATED by tools/extract_font.py -- do not edit.\n"
        "// 4096 bytes: 256 glyphs x 16 rows, MSB = leftmost pixel.\n"
        "// Derived from linux-7.2.8/lib/fonts/font_8x16.c (GPL-2.0).\n"
    )
    with open(js_path, "w") as fh:
        fh.write(header)
        fh.write(f'window.LW = window.LW || {{}};\nwindow.LW.FONT_B64 = "{b64}";\n')

    print(f"  wrote {os.path.relpath(bin_path, root)} ({len(data)} bytes)")
    print(f"  wrote {os.path.relpath(js_path, root)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("tarball", nargs="?", default=DEFAULT_TARBALL)
    args = ap.parse_args()

    print(f"reading {FONT_MEMBER} (tarball: {args.tarball})")
    text = read_font_source(args.tarball)
    data = parse_font(text)
    print(f"parsed {len(data)} bytes of glyph data")
    self_test(data)
    write_assets(data)
    print("font extraction OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
