#!/usr/bin/env python3
"""Extract bash 5.3's real banner/version strings from its source tree.

Source: /home/Yin/Downloads/bash-5.3.tar.gz.  Every string is anchored to the
file it comes from and asserted present, so the shell can never silently drift
away from bash 5.3.

Outputs src/bash.data.js:

    window.LW.BASH = { version, patchLevel, buildVersion, versionString,
                       machtype, copyright, license, freeSoftware, noWarranty,
                       pprompt, sprompt }
"""

import argparse
import json
import os
import re
import subprocess
import sys

DEFAULT_TARBALL = "/home/Yin/Downloads/bash-5.3.tar.gz"
PREFIX = "bash-5.3/"

FILES = {
    "configure.ac": PREFIX + "configure.ac",
    "patchlevel.h": PREFIX + "patchlevel.h",
    "version.c": PREFIX + "version.c",
    "config-top.h": PREFIX + "config-top.h",
}

# bash's `bash --version` prints this host triplet (configure's $host).
MACHTYPE = "x86_64-pc-linux-gnu"


def root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def read_sources(tarball: str) -> dict:
    cache = os.path.join(root(), "tools", ".cache", "bash")
    os.makedirs(cache, exist_ok=True)
    out = {}
    for name, member in FILES.items():
        path = os.path.join(cache, name)
        if not os.path.exists(path):
            if not os.path.exists(tarball):
                raise SystemExit(
                    f"{name} is not cached and the tarball ({tarball}) is missing"
                )
            data = subprocess.check_output(["tar", "-xzOf", tarball, member])
            with open(path, "wb") as fh:
                fh.write(data)
        with open(path, "rb") as fh:
            out[name] = fh.read().decode("latin-1")
    return out


def grab(pattern: str, text: str, what: str) -> str:
    m = re.search(pattern, text)
    if not m:
        raise SystemExit(f"anchor not found for {what}: /{pattern}/")
    return m.group(1)


def build(src: dict) -> dict:
    ac, pl, ver, cth = (src["configure.ac"], src["patchlevel.h"],
                        src["version.c"], src["config-top.h"])

    version = grab(r"define\(bashvers,\s*([0-9.]+)\)", ac, "bashvers")
    relstatus = grab(r"define\(relstatus,\s*(\w+)\)", ac, "relstatus")
    patch = int(grab(r"#define\s+PATCHLEVEL\s+(\d+)", pl, "PATCHLEVEL"))

    # version.c: shell_version_string() composes "<dist>.<patch>(<build>)-<rel>"
    banner_fmt = grab(r'printf \(_?\("(GNU bash, version %s \(%s\)\\n)"', ver, "banner")
    assert banner_fmt == "GNU bash, version %s (%s)\\n", banner_fmt
    copyright = grab(r'bash_copyright\s*=\s*N_\("([^"]+)"\)', ver, "copyright")
    license_ = grab(r'bash_license\s*=\s*N_\("([^"]+)"\)', ver, "license")
    free_software = grab(
        r'_?\(\s*"(This is free software; you are free to change and redistribute it\.)"\s*\)',
        ver, "free software",)
    no_warranty = grab(
        r'_?\(\s*"(There is NO WARRANTY, to the extent permitted by law\.)"\s*\)',
        ver, "no warranty")

    # config-top.h: the built-in prompts (default PS1/PS2)
    ppropmt = grab(r'#define\s+PPROMPT\s+"((?:\\.|[^"])*)"', cth, "PPROMPT")
    sprompt = grab(r'#define\s+SPROMPT\s+"((?:\\.|[^"])*)"', cth, "SPROMPT")

    build_version = 1  # released tarballs default to build 1
    version_string = f"{version}.{patch}({build_version})-{relstatus}"

    return {
        "version": version,
        "patchLevel": patch,
        "buildVersion": build_version,
        "releaseStatus": relstatus,
        "versionString": version_string,
        "machtype": MACHTYPE,
        "banner": banner_fmt,
        "copyright": copyright,
        "license": license_,
        "freeSoftware": free_software,
        "noWarranty": no_warranty,
        "pprompt": ppropmt,
        "sprompt": sprompt,
    }


def write_output(data: dict) -> None:
    path = os.path.join(root(), "src", "bash.data.js")
    header = (
        "// GENERATED by tools/gen_bash_strings.py -- do not edit.\n"
        "// Banner/version strings taken from bash-5.3 (version.c, configure.ac,\n"
        "// patchlevel.h, config-top.h).\n"
    )
    with open(path, "w") as fh:
        fh.write(header)
        fh.write("window.LW = window.LW || {};\n")
        fh.write("window.LW.BASH = " + json.dumps(data, indent=2) + ";\n")
    print("  wrote src/bash.data.js")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("tarball", nargs="?", default=DEFAULT_TARBALL)
    args = ap.parse_args()

    src = read_sources(args.tarball)
    data = build(src)
    print(f"bash {data['versionString']} ({data['machtype']})")
    print(f"  PPROMPT={data['pprompt']!r} SPROMPT={data['sprompt']!r}")
    write_output(data)
    print("bash strings OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
