#!/usr/bin/env python3
"""Generate src/procps_help.js.

ps, pgrep, pkill and pidof belong to procps-ng and pstree to psmisc, not to
coreutils, so their help/version text cannot live in coreutils_help.js.
This script runs the real programs with LC_ALL=C and writes their verbatim
output into a lookup table, the same way gen_coreutils_help.py does for the
coreutils.

    python3 tools/gen_procps_help.py

The captured text is GPL-2.0 text from procps-ng / psmisc, reproduced so that
`ps --help` here prints what `ps --help` prints on a real machine.
"""

import os
import subprocess
import sys

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                   "src", "procps_help.js")

HEADER = """// GENERATED by tools/gen_procps_help.py -- do not edit by hand.
//
// The verbatim help, version and specifier text of the procps-ng programs
// this page implements (ps, pgrep, pkill, pidof) and of psmisc's pstree,
// captured from the real binaries with LC_ALL=C.
//
//   LW.PSHELP.ps[""]        -> the lines of `ps --help`
//   LW.PSHELP.ps["all"]     -> the lines of `ps --help all`
//   LW.PSHELP.psSpec        -> the lines of `ps L`
//   LW.PSHELP.pgrep         -> the lines of `pgrep --help`
//   LW.PSHELP.pstreeUsage   -> the usage text of pstree(1)
//   LW.PSVER.ps             -> the lines of `ps --version`
//   LW.PSVER.pstree         -> the lines of `pstree -V`
//
// src/procps.js reads these; nothing else should.
"""

# key -> argv; "help" keys are sorted into LW.PSHELP, "spec"/"usage" go there
# too, and keys ending in "ver" become LW.PSVER.
CAPTURES = [
    ("psHelp",      ["ps", "--help"],            "stdout"),
    ("psHelp.simple", ["ps", "--help", "simple"], "stdout"),
    ("psHelp.list", ["ps", "--help", "list"],    "stdout"),
    ("psHelp.output", ["ps", "--help", "output"], "stdout"),
    ("psHelp.threads", ["ps", "--help", "threads"], "stdout"),
    ("psHelp.misc", ["ps", "--help", "misc"],    "stdout"),
    ("psHelp.all",  ["ps", "--help", "all"],     "stdout"),
    ("psSpec",      ["ps", "L"],                 "stdout"),
    ("psVer",       ["ps", "--version"],         "stdout"),
    ("pgrepHelp",   ["pgrep", "--help"],         "stdout"),
    ("pgrepVer",    ["pgrep", "--version"],      "stdout"),
    ("pkillHelp",   ["pkill", "--help"],         "stdout"),
    ("pkillVer",    ["pkill", "--version"],      "stdout"),
    ("pidofHelp",   ["pidof", "-h"],             "stdout"),
    # `pstree -V` writes its banner to stderr, unlike every --version above.
    ("pstreeVer",   ["pstree", "-V"],            "stderr"),
    ("pstreeUsage", ["pstree", "--bogus"],       "stderr"),
]

# getopt complains about the bogus option before psmisc prints the usage
# text; the complaint belongs to the run, not to the text being captured.
LEADIN = {"pstreeUsage": 1}


def json_str(s):
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    out = out.replace("\t", "\\t").replace("\r", "\\r")
    return '"' + out + '"'


def lines(text):
    if text.endswith("\n"):
        text = text[:-1]
    return text.split("\n") if text else []


def capture(argv, stream, env):
    """Run argv and return the wanted stream as text, or None if missing."""
    try:
        p = subprocess.run(argv, capture_output=True, timeout=30, env=env)
    except OSError:
        return None
    blob = p.stdout if stream == "stdout" else p.stderr
    return blob.decode("utf-8", "replace")


def emit_array(f, name, text, indent):
    pad = " " * indent
    f.write("%s%s: [\n" % (pad, name))
    for line in lines(text):
        f.write("%s  %s,\n" % (pad, json_str(line)))
    f.write("%s],\n" % pad)


def main():
    env = dict(os.environ, LC_ALL="C")
    got = {}
    for key, argv, stream in CAPTURES:
        text = capture(argv, stream, env)
        if text is None:
            print("skip %s (not installed)" % argv[0], file=sys.stderr)
            continue
        got[key] = text
        drop = LEADIN.get(key, 0)
        if drop and "\n" in text:
            got[key] = text.split("\n", drop)[drop]

    with open(OUT, "w") as f:
        f.write(HEADER)
        f.write('(function (LW) {\n  "use strict";\n\n')

        # --- LW.PSHELP: the ps help categories, the other tools' help, the
        # --- `ps L` specifier table and pstree's usage text.
        f.write("  LW.PSHELP = {\n")
        f.write("    ps: {\n")
        for key in ["psHelp", "psHelp.simple", "psHelp.list", "psHelp.output",
                    "psHelp.threads", "psHelp.misc", "psHelp.all"]:
            if key in got:
                cat = key.split(".", 1)[1] if "." in key else ""
                emit_array(f, '"%s"' % cat, got[key], 6)
        f.write("    },\n")
        for key in ["psSpec", "pgrepHelp", "pkillHelp", "pidofHelp",
                    "pstreeUsage"]:
            if key in got:
                name = key[:-4] if key.endswith("Help") else key
                emit_array(f, name, got[key], 4)
        f.write("  };\n\n")

        # --- LW.PSVER: `--version` output.
        f.write("  LW.PSVER = {\n")
        for key in ["psVer", "pgrepVer", "pkillVer", "pstreeVer"]:
            if key in got:
                emit_array(f, key[:-3], got[key], 4)
        f.write("  };\n")
        f.write("})(window.LW = window.LW || {});\n")

    total = sum(len(lines(t)) for t in got.values())
    print("wrote %s (%d lines of captured text from %d commands)"
          % (OUT, total, len(got)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
