#!/usr/bin/env python3
"""Generate src/coreutils_help.js.

Every GNU coreutils program answers `--help` and `--version` with its own
verbatim text.  This script runs the real binaries (LC_ALL=C, so the wording
is the English coreutils text and not a translation) and writes the output
into a lookup table, the same way gen_bash_help.py turns bash's
builtins/*.def into src/help.js.

    python3 tools/gen_coreutils_help.py [BINDIR]

BINDIR defaults to $PATH.  Programs that are not installed are skipped with
a note; the generated file only ever contains what really was captured.
"""

import json
import os
import subprocess
import sys

# The GNU coreutils 9.x programs (see `dpkg -L coreutils`).  Scripts with a
# different origin (grep, sed, find, rev, ps, ...) are deliberately absent:
# their help text is not coreutils' to copy.
PROGRAMS = [
    "arch", "b2sum", "base32", "base64", "basename", "basenc", "cat", "chcon",
    "chgrp", "chmod", "chown", "cksum", "comm", "cp", "csplit", "cut", "date",
    "dd", "df", "dir", "dircolors", "dirname", "du", "echo", "env", "expand",
    "expr", "factor", "false", "fmt", "fold", "groups", "head", "hostid", "id",
    "install", "join", "link", "ln", "logname", "ls", "md5sum", "mkdir",
    "mkfifo", "mknod", "mktemp", "mv", "nice", "nl", "nohup", "nproc",
    "numfmt", "od", "paste", "pathchk", "pinky", "pr", "printenv", "printf",
    "ptx", "pwd", "readlink", "realpath", "rm", "rmdir", "runcon", "seq",
    "sha1sum", "sha224sum", "sha256sum", "sha384sum", "sha512sum", "shred",
    "shuf", "sleep", "sort", "split", "stat", "stdbuf", "stty", "sum", "sync",
    "tac", "tail", "tee", "test", "timeout", "touch", "tr", "true", "truncate",
    "tsort", "tty", "uname", "unexpand", "uniq", "unlink", "users", "vdir",
    "wc", "who", "whoami", "yes",
]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                   "src", "coreutils_help.js")

HEADER = """// GENERATED by tools/gen_coreutils_help.py -- do not edit by hand.
//
// The verbatim `--help` and `--version` text of the GNU coreutils programs
// this page implements, captured from the real binaries with LC_ALL=C.
// It is GPL-3.0 text from GNU coreutils 9.x, reproduced so that
// `cat --help` here prints what `cat --help` prints on a real machine.
//
//   LW.CUHELP["cat"]  ->  the lines of `cat --help`
//   LW.CUVER["cat"]   ->  the lines of `cat --version`
//
// LW.core.doc(name, "help" | "version") in bash.js joins them back up.
"""


def capture(prog, flag, env):
    """Run `prog flag`, return its output, or None if it is not installed.

    --help goes to stdout and exits 0; a few programs (true, false) print it
    on the way to a non-zero status, so neither stream nor status decides --
    an empty capture does.
    """
    try:
        r = subprocess.run([prog, flag], stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, env=env, timeout=15)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    out = r.stdout or r.stderr
    return out.decode("utf-8", "replace") or None


def js_table(name, table):
    """One array of output lines per program, the way src/help.js stores it."""
    lines = ["  LW.%s = {" % name]
    for key in sorted(table):
        rows = table[key].split("\n")
        if rows and rows[-1] == "":
            rows.pop()                      # the trailing newline is implicit
        body = "\n".join("      " + json.dumps(r) + "," for r in rows)
        lines.append("    %s: [\n%s\n    ]," % (json.dumps(key), body))
    lines.append("  };")
    return "\n".join(lines)


def main():
    env = dict(os.environ, LC_ALL="C")
    if len(sys.argv) > 1:
        env["PATH"] = os.path.abspath(sys.argv[1]) + os.pathsep + env.get("PATH", "")

    help_t, ver_t, missing = {}, {}, []
    for prog in PROGRAMS:
        htext = capture(prog, "--help", env)
        if htext is None:
            missing.append(prog)
            continue
        vtext = capture(prog, "--version", env)
        help_t[prog] = htext
        if vtext:
            ver_t[prog] = vtext

    body = (HEADER + "(function (LW) {\n  \"use strict\";\n\n" +
            js_table("CUHELP", help_t) + "\n\n" +
            js_table("CUVER", ver_t) +
            "\n})(window.LW = window.LW || {});\n")
    with open(OUT, "w") as fh:
        fh.write(body)

    print("wrote %s: %d --help, %d --version" %
          (os.path.relpath(OUT), len(help_t), len(ver_t)))
    if missing:
        print("skipped (not installed): " + " ".join(missing))
    return 0


if __name__ == "__main__":
    sys.exit(main())
