// GENERATED by tools/gen_bash_strings.py -- do not edit.
// Banner/version strings taken from bash-5.3 (version.c, configure.ac,
// patchlevel.h, config-top.h).
window.LW = window.LW || {};
window.LW.BASH = {
  "version": "5.3",
  "patchLevel": 0,
  "buildVersion": 1,
  "releaseStatus": "release",
  "versionString": "5.3.0(1)-release",
  "machtype": "x86_64-pc-linux-gnu",
  "banner": "GNU bash, version %s (%s)\\n",
  "copyright": "Copyright (C) 2025 Free Software Foundation, Inc.",
  "license": "License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\\n",
  "freeSoftware": "This is free software; you are free to change and redistribute it.",
  "noWarranty": "There is NO WARRANTY, to the extent permitted by law.",
  "pprompt": "\\\\s-\\\\v\\\\$ ",
  "sprompt": "> "
};
